### PR TITLE
Reorganize NUG to separate standards and best practices from implementation details

### PR DESCRIPTION
**Pull request by ethanrd**

### CODE REVIEW

**Comment by ethanrd** [comment]
OK. I think this is good for a first pass. Three big things: 1) decide on how to split data model content; 2) move file format content from doxygen docs into markdown docs; and 3) Update the CDL content with text from ncdump/ncgen man pages. Lots of other decisions and text to clean up but those are the big ones.

I'll mark ready for review/merge.

**Comment by WardF** [comment]
I think the issue is that the GitHub action needs updated; I'm going to merge and then will fix that.

**Comment by ddirks** [comment]
I have no special insights into this, and I think it's already merged. But I'm not sure how to remove the request for my review...

**Comment by WardF** [comment]
@ddirks I went ahead and removed, thanks!

**Pull request merged**
